ALTER TABLE users
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;

UPDATE users
SET created_at = CURRENT_TIMESTAMP
WHERE created_at IS NULL;

ALTER TABLE users
    ALTER COLUMN created_at SET NOT NULL;
